### PR TITLE
37017519 add version number to api

### PR DESCRIPTION
**Pull request by ke4**

### CODE REVIEW

**Comment by ke4** [comment]
I'm cancelling this request because we should probably rework it to use the existing 'revision' system that is currently used to distinguish between version 1 and 2.

**Comment by ke4** [comment]
The changes have been made.

**Comment by ke4** [comment]
We moved the version number from the encoder to the context and checked with Matthew it should only be on the root JSON.

**Comment by maxigit** [comment]
Could you rebase please. This pull request cannot be automatically merged.

**Comment by ke4** [comment]
We have rebased it on the latest development branch.

**Pull request merged**
